version: "2.1"

services:
  db:
    image: "postgres:15.2"
    expose:
      - "5432"  # Internal container port exposed (not accessible by the host machine)
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh  # create user and databases
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    env_file: .env
    environment:
      PROCESS_TYPE: "web"
    ports:
      - "8000:80"
    volumes:
      - .:/code
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
  broker:
    image: "rabbitmq"
  worker:
    build: .
    env_file: .env
    environment:
      PROCESS_TYPE: "worker"
    volumes:
      - .:/code
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
  beat:
    build: .
    env_file: .env
    environment:
      PROCESS_TYPE: "beat"
    volumes:
      - .:/code
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started

volumes:
  db-data:

networks:
  default:
