"""Initial migration

Revision ID: 5f32fdb6cc65
Revises: 
Create Date: 2023-05-19 18:45:56.957421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f32fdb6cc65"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("link", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=255), nullable=True),
        sa.Column("last_build_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
    )
    op.create_index(op.f("ix_feed_id"), "feed", ["id"], unique=False)
    op.create_index(
        op.f("ix_feed_last_build_date"), "feed", ["last_build_date"], unique=False
    )
    op.create_index(op.f("ix_feed_title"), "feed", ["title"], unique=True)
    op.create_index(op.f("ix_feed_uuid"), "feed", ["uuid"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=False)
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=True)
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("link", sa.String(length=255), nullable=False),
        sa.Column("pub_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
    )
    op.create_index(op.f("ix_post_id"), "post", ["id"], unique=False)
    op.create_index(op.f("ix_post_pub_date"), "post", ["pub_date"], unique=False)
    op.create_index(op.f("ix_post_title"), "post", ["title"], unique=True)
    op.create_index(op.f("ix_post_uuid"), "post", ["uuid"], unique=True)
    op.create_table(
        "user_feed",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "feed_id"),
    )
    op.create_table(
        "user_post",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_post")
    op.drop_table("user_feed")
    op.drop_index(op.f("ix_post_uuid"), table_name="post")
    op.drop_index(op.f("ix_post_title"), table_name="post")
    op.drop_index(op.f("ix_post_pub_date"), table_name="post")
    op.drop_index(op.f("ix_post_id"), table_name="post")
    op.drop_table("post")
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_feed_uuid"), table_name="feed")
    op.drop_index(op.f("ix_feed_title"), table_name="feed")
    op.drop_index(op.f("ix_feed_last_build_date"), table_name="feed")
    op.drop_index(op.f("ix_feed_id"), table_name="feed")
    op.drop_table("feed")
    # ### end Alembic commands ###
